#!/bin/tcsh
#PBS -N asg:cnn-s2
#PBS -l nodes=3:c18x:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe

# mpirun --mca mpi_warn_on_fork 0 --map-by node python-mpi /sciclone/aiddata10/REU/projects/mcc_tanzania/s2_main.py
