#!/bin/tcsh
#PBS -N asg:cnn-s32
#PBS -l nodes=1:c18x:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe

# mpirun --mca mpi_warn_on_fork 0 --map-by node python-mpi /sciclone/aiddata10/REU/projects/mcc_tanzania/s3_s2_predict.py
